name: Update Last Updated Date
permissions:
  contents: write

on:
  push:
    branches:
      - main  # or 'master' if that's your main branch

jobs:
  update_last_updated_date:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get current date and time
        id: date_time
        run: |
          # Get current date and time in the format: "Month Day, Year HH:MM:SS"
          CURRENT_DATE=$(date "+%Y-%m-%d %H:%M:%S")  # Format to include the time (Hour:Minute:Second)
          echo "CURRENT_DATE=${CURRENT_DATE}" >> $GITHUB_ENV
          echo "Debug - Current Date and Time: $CURRENT_DATE"  # Debug step to confirm time format

      - name: Check for last-updated element and update the time
        run: |
          # Check if the element with class "last-updated" exists
          if grep -q 'class="last-updated"' index.html; then
            # If the element exists, replace its content with the current date and time
            sed -i 's|<div class="last-updated">.*</div>|<div class="last-updated">Last Updated: ${CURRENT_DATE}</div>|' index.html
          else
            # If the element doesn't exist, append the element to the body (or wherever you'd like it)
            echo "<div class='last-updated'>Last Updated: ${CURRENT_DATE}</div>" >> index.html
          fi

      - name: Print the contents of index.html
        run: |
          cat index.html  # This will display the contents of the index.html to confirm if the time is updated correctly

      - name: Check if changes were made
        run: |
          git diff --exit-code || echo "Changes detected, committing..."

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add index.html
          git commit -m "Update last updated date and time" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
