name: Update Last Updated Date
permissions:
  contents: write  # Allow write access to the repository contents (necessary for pushing changes)


on:
  push:
    branches:
      - main  # or 'master' if that's your main branch

jobs:
  update_last_updated_date:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get current date and time
        id: date_time
        run: |
          # Get current date and time in the format: "Month Day, Year HH:MM:SS"
          CURRENT_DATE=$(date "+%B %d, %Y %H:%M:%S")
          echo "CURRENT_DATE=${CURRENT_DATE}" >> $GITHUB_ENV

      - name: Replace placeholder with the last commit date
        run: |
          # Use sed to replace the placeholder with the formatted date
          sed -i "s/<!-- LAST_UPDATED_PLACEHOLDER -->/${{ env.LAST_COMMIT_DATE }}/" index.html

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add index.html
          git commit -m "Update last updated date"
          git push
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
